apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metrics-scaledobject
spec:
  maxReplicaCount: 10
  scaleTargetRef:
    name: webapp
  triggers:
  - type: metrics-api
    metadata:
      targetValue: "5"
      url: "https://z4nbs46q-5062.brs.devtunnels.ms/Metrics"
      valueLocation: 'currentValue'